### ISSUE TITLE
EPIC: Upgrade Keycloak to the latest version

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/authentication-server#66]
- [x] Upgrade Keycloak to the newest version (starting from 21.03)
- [ ] #59 
- [x] #61 
- [ ] #60

**Comment by mmalfertheiner** [comment]
- [ x] Development mode should allow to update theme on the fly for good DX
- [ ] prefix base path with /auth, like it was before v17
- [ ] integrate and test registration listener
- [ ] production deployment with multiple nodes
